base {
        log_debug = off;
        log_info = on;
        log = "syslog:local7";
        daemon = on;
        redirector = iptables;
}

redsocks {
        local_ip = 0.0.0.0;
        local_port = 1181;
        ip = 192.168.1.125;
        port = 9001;
        type = socks5;
}

redsocks {
        local_ip = 0.0.0.0;
        local_port = 1182;
        ip = 192.168.1.125;
        port = 9002;
        type = socks5;
}

redsocks {
        local_ip = 0.0.0.0;
        local_port = 1183;
       ip = 192.168.1.125;
        port = 9003;
        type = socks5;
}

redsocks {
        local_ip = 0.0.0.0;
        local_port = 1184;
       ip = 192.168.1.125;
        port = 9004;
        type = socks5;
}
