base {
        log_debug = off;
        log_info = on;
        log = "syslog:local7";
        daemon = on;
        redirector = iptables;
}

redsocks {
        local_ip = 192.168.1.181;
        local_port = 9001;
        ip = 5.252.52.117;
        port = 9701;
        type = socks5;
}
redsocks {
        local_ip = 192.168.1.182;
        local_port = 1181;
        ip = 5.252.52.117;
        port = 9801;
        type = socks5;
}
redsocks {
        local_ip = 192.168.1.183;
        local_port = 1183;
        ip = 5.252.52.117;
        port = 9701;
        type = socks5;
}
redsocks {
        local_ip = 192.168.1.184;
        local_port = 1184;
        ip = 5.252.52.117;
        port = 9801;
        type = socks5;
}