base {
        log_debug = off;
        log_info = on;
        log = "syslog:local7";
        daemon = on;
        redirector = iptables;
}

redsocks {
        local_ip = 0.0.0.0;
        local_port = 9001;
        ip = 5.252.52.117;
        port = 9701;
        type = socks5;
}
